package main

import (
	"encoding/json"
	"log"
	"sync"

	maelstrom "github.com/jepsen-io/maelstrom/demo/go"
)

func main() {
	n := maelstrom.NewNode()
	serv := &server{n: n, seen_set: make(map[int]struct{})}
	n.Handle("broadcast", serv.receive_broadcast)
	n.Handle("read", serv.read_broadcast)
	n.Handle("topology", serv.receive_topology)

	if err := n.Run(); err != nil {
		log.Fatal(err)
	}
}

type server struct {
	n        *maelstrom.Node
	seen_set map[int]struct{}
	seen_mutex  sync.Mutex
	neighbors map[string]map[int]struct{}
}

func (s *server) receive_broadcast(msg maelstrom.Message) error {
	var body map[string]interface{}
	if err := json.Unmarshal(msg.Body, &body); err != nil {
		return err
	}
	var received_int int = int(body["message"].(float64))
	s.seen_mutex.Lock()
	// If we have not seen the message before, keep track of it and broadcast it to all peers.
	if _, ok := s.seen_set[received_int]; !ok {
		s.seen_set[received_int] = struct{}{}
		msg_body := map[string]interface{}{
			"message":        received_int,
			"type":           "broadcast",
			"node_generated": true,
		}
		msg_body_byte, err := json.Marshal(msg_body)
		if err != nil {
			return err
		}
		var msg_body_jsonned = json.RawMessage(msg_body_byte)
		for peer := range s.neighbors {
			var retrySend func (msg maelstrom.Message) error
			retrySend = func (msg maelstrom.Message) error {
				if msg.RPCError() != nil {
					return s.n.RPC(peer, msg_body_jsonned, retrySend)
				}
				return nil
			}
			s.n.RPC(peer, msg_body_jsonned, retrySend)
		}
	}
	s.seen_mutex.Unlock()
	// If the message was generated by a node and not maelstrom, don't reply.
	if _, ok := body["node_generated"]; ok {
		return nil
	}
	delete(body, "message")
	body["type"] = "broadcast_ok"
	return s.n.Reply(msg, body)
}

func (s *server) read_broadcast(msg maelstrom.Message) error {
	var body map[string]any
	if err := json.Unmarshal(msg.Body, &body); err != nil {
		return err
	}
	body["type"] = "read_ok"
	s.seen_mutex.Lock()
	// Convert the set to a list and send that back.
	var result []int = make([]int, 0, len(s.seen_set))
	for id := range s.seen_set {
		result = append(result, id)
	}
	s.seen_mutex.Unlock()
	body["messages"] = result
	return s.n.Reply(msg, body)
}

func (s *server) receive_topology(msg maelstrom.Message) error {
	var body map[string]any
	if err := json.Unmarshal(msg.Body, &body); err != nil {
		return err
	}
	s.neighbors = make(map[string]map[int]struct{})
	for k, v := range body["topology"].(map[string]interface{}) {
		// If the key is this node, add all the neighbors to the topology map, along with an empty list as their value
		if k == s.n.ID() {
			for _, neighbor := range v.([]interface{}) {
				s.neighbors[neighbor.(string)] = make(map[int]struct{})
			}
		}
	}
	delete(body, "topology")
	body["type"] = "topology_ok"
	return s.n.Reply(msg, body)
}
